name: workout_plan_builder
description: A Flutter app for fitness trainers and clients with workout plan builder.
publish_to: 'none' # Remove this line if you plan to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core domain packages
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Firebase (for later integration)
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
